<?xml version="1.0"?>
<!-- COPYRIGHT 2002 PolyGlot, Inc. -->

<!-- this stylesheet decl is for IE 5.0 not IE 5.5+ -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/TR/WD-xsl" version="1.0">

    <xsl:template match="text()">
         <xsl:apply-templates/>
    </xsl:template>


    <xsl:template match="/">
       <html>
       <head></head>
       <body>
       <p><i>[FYI, This browser chose this XSL stylesheet which is meant for IE/4/5/5.5
       without msxml2 in replace mode]</i></p>

<!-- xsl:for-each select="//person" -->
       <xsl:apply-templates select="//person"/><br/>(generated by your browser from XML data using XSL)<br/><br/>
<!-- /xsl:for-each -->

<table title="Alphabetical CLIENT Summary">
<th bgcolor="orange">Alphabetical CLIENT Summary</th>
<xsl:for-each select="//client" order-by="@name">
  <!-- xsl:sort select="@name" / -->
<tr><td><b><xsl:value-of select="@name"/></b> : <xsl:value-of select="@location"/></td>
    <td><FONT SIZE="-1"><b><i><xsl:value-of select="../short_desc"/></i></b></FONT><br/></td>
</tr>
</xsl:for-each>
</table>
<p/>
       <!-- div style="border: solid 3px red; padding: 10px;" -->
<table title="Chronological PROJECT Details">
<th bgcolor="red">Chronological PROJECT Details</th>
<xsl:for-each select="//person">
         <xsl:apply-templates select="project"/>
     <!-- xsl:apply-templates select="project[description!='']"/ -->
</xsl:for-each>
</table>
       <!-- /div -->
       </body>
       </html>
    </xsl:template>


    <xsl:template match="*">
         <xsl:apply-templates/>
    </xsl:template>

    <xsl:template match="person">
        Resume of <b><xsl:value-of select="@name"/></b> :
        <xsl:value-of select="phone"/> ;
        <xsl:value-of select="email"/>
        <!-- ul><xsl:apply-templates/></ul  -->
    </xsl:template>


    <xsl:template match="project">
<TR>
  <TD VALIGN="top"> <!-- width="250" -->
    <TABLE bgcolor="#EEEEEE" WIDTH="100%" BORDER="1"><TR><TD>
      <TABLE><TR><TD nowrap="nowrap"><FONT SIZE="2"><xsl:value-of select="@start"/> thru <xsl:value-of select="@end"/>: <xsl:apply-templates select="position"/>
                     <BR/><xsl:apply-templates select="client[@name]"/>
                     <BR/><xsl:apply-templates select="supervisor[@name!='']"/></FONT></TD></TR>
             <TR><TD><B><FONT SIZE="-1">KEYWORDS: </FONT></B><FONT SIZE="-2"><xsl:apply-templates select="keywords[@list]"/></FONT></TD></TR>
      </TABLE></TD></TR>
    </TABLE>
  </TD>
  <TD VALIGN="top"><FONT SIZE="-1"><xsl:value-of select="description"/>
                                   <xsl:apply-templates select="staff[@headcount]"/></FONT></TD>
</TR>

<!--
       <br/><li>
          <xsl:apply-templates select="client"/><br/>
          <xsl:apply-templates select="position"/><br/>
          <b><i><xsl:value-of select="short_desc"/></i></b><br/>
          <!- - xsl:value-of select="description"/ - ->
       </li>
-->
    </xsl:template>

<!-- IE5.0 cant do xsl:if and xsl:choose so we have some redundancy here... -->
    <xsl:template match="project[description='']">
<TR>
  <TD VALIGN="top"> <!-- width="250" -->
    <TABLE bgcolor="#EEEEEE" WIDTH="100%" BORDER="1"><TR><TD>
      <TABLE><TR><TD nowrap="nowrap"><FONT SIZE="2"><xsl:value-of select="@start"/> thru <xsl:value-of select="@end"/>: <xsl:apply-templates select="position"/>
                     <BR/><xsl:apply-templates select="client[@name]"/>
                     <BR/><xsl:apply-templates select="supervisor[@name!='']"/></FONT></TD></TR>
             <TR><TD><B><FONT SIZE="-1">KEYWORDS: </FONT></B><FONT SIZE="-2"><xsl:apply-templates select="keywords[@list]"/></FONT></TD></TR>
      </TABLE></TD></TR>
    </TABLE>
  </TD>
  <TD VALIGN="top"><FONT SIZE="-1"><i><xsl:value-of select="short_desc"/>
                                      <xsl:apply-templates select="staff[@headcount]"/></i></FONT></TD>
</TR>
    </xsl:template>

<!-- IE5.0 cant do xsl:if and xsl:choose so we have some redundancy here... -->
    <xsl:template match="staff[@headcount!='0']">
<u>Directed the efforts of <xsl:value-of select="@headcount"/> other developers.</u>
    </xsl:template>

    <xsl:template match="client">
          <small><u>CLIENT:</u></small> <b><xsl:value-of select="@name"/></b> : <xsl:value-of select="@location"/>
    </xsl:template>

    <xsl:template match="position">
          <!-- small><u>TITLE:</u></small -->
          <b><xsl:value-of select="@title"/></b> <i> [<xsl:value-of select="@type"/>]</i>
    </xsl:template>

    <xsl:template match="client[@name]">
          <xsl:value-of select="@name"/>, <xsl:value-of select="@location"/>
    </xsl:template>

    <xsl:template match="supervisor[@name]">
          <xsl:value-of select="@name"/>, <xsl:value-of select="@title"/>
    </xsl:template>

    <xsl:template match="keywords[@list]">
          <xsl:value-of select="@list"/>
    </xsl:template>

</xsl:stylesheet>

